# Site settings
title: Documentação Pagar.me
email: contato@pagar.me
description: "Documentação Pagar.me"
baseurl: ""
url: "https://pagar.me/docs"

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: expanded
    deploy_style: compressed
    compile_in_place: false
highlighteiir: true
gems: [jekyll-sass]

